### PR TITLE
feat: Implement Rendezvous module in py-libp2p

### PR DESCRIPTION
**Pull request by sumanjeet0012**
## What was wrong?

Fixes https://github.com/libp2p/py-libp2p/issues/898

The py-libp2p library lacked a Rendezvous protocol implementation for peer discovery. This missing functionality created a gap between py-libp2p and other libp2p implementations (Go, Rust) that already support rendezvous-based peer discovery through namespaces.

### 1. Core Module Implementation

- **`libp2p/discovery/rendezvous/`** directory with complete protocol implementation:
  - `service.py`: Rendezvous service handling peer registrations and discovery
  - `client.py`: Low-level protocol client with trio structured concurrency
  - `discovery.py`: High-level discovery interface with caching and auto-refresh
  - `config.py`: Configuration constants and defaults
  - `errors.py`: Protocol-specific exception classes
  - `messages.py`: Protocol buffer message utilities
  - `pb/rendezvous_pb2.py`: Protocol buffer definitions

### 2. Key Features

- **Peer Registration**: Advertise peers under namespaces with configurable TTL
- **Peer Discovery**: Find peers by namespace with pagination support
- **Auto-refresh**: Trio-based automatic re-registration before TTL expiry using structured concurrency
- **Caching**: Discovery result caching with TTL management to reduce repeated queries
- **Resource Management**: Clean startup/shutdown with proper trio nursery lifecycle
- **Error Handling**: Comprehensive error types with proper null response handling
- **Type Safety**: Full mypy compatibility with proper Optional/Union type annotations

### 3. Protocol Compliance

- Full libp2p rendezvous protocol specification compliance
- Protocol buffer message serialization/deserialization
- Pagination support with limit and cookie-based navigation
- Proper error status handling and propagation
- Trio structured concurrency for reliable background operations

### 4. Examples and Integration

- Complete example demonstrating server and client usage in `examples/rendezvous/`
- Command-line interface for testing (`--mode server/client/discover`)
- Optional refresh functionality showcase with trio nursery management
- Seamless integration with existing py-libp2p host implementation
- Proper logging integration with configurable debug output

### 5. Documentation and Testing

- **Comprehensive Documentation**: 
  - `docs/examples.rendezvous.rst`: Complete user guide with tutorials and real log outputs
  - `docs/libp2p.discovery.rendezvous.rst`: Full API documentation with cross-references
  - Sphinx build integration with proper toctree structure
- **Type Safety**: All mypy type checking errors resolved
- **Logging Integration**: Proper propagation configuration for debug visibility
- **Release Notes**: Added newsfragment documenting the new feature

## Benefits

- **Feature Parity**: Brings py-libp2p closer to other libp2p implementations
- **Flexible Discovery**: Application-specific peer discovery patterns with namespace organization
- **Bootstrap Alternative**: Lightweight alternative to DHT-based discovery
- **Namespace Organization**: Logical grouping of peers by service type

## To-Do

- [ ] Clean up commit history
- [ ] Add documentation updates
- [ ] Add entry to release notes

### CODE REVIEW

**Comment by sumanjeet0012** [comment]
@seetadev @pacrob Rendezvous is working as expected, This PR is now ready for review.

**Comment by seetadev** [comment]
Great work @sumanjeet0012 🎉

This is a very important addition to py-libp2p, and I really appreciate the level of depth and completeness you’ve brought into the Rendezvous implementation.

Thank you for keeping a note of each of these important aspects/ features:

- Protocol compliance (peer registration, discovery, pagination, error handling)

-  Trio-based structured concurrency for auto-refresh and lifecycle management

- Type safety and mypy compatibility

- Documentation + examples that make it much easier for new contributors to try it out.

- Logging integration and user-friendly CLI for testing

Wish if you could add a small document/discussion page along with a screencast recording/demo for the implementation. We will play it during the upcoming maintainer's meeting.

This closes a long-standing gap between py-libp2p and other implementations like Go/Rust, and brings us much closer to feature parity in peer discovery. The namespace-based discovery patterns also give developers a lot of flexibility beyond just bootstrapping or DHT-based methods.

Thanks again for pushing this forward — it’s a big step for the project.

CCing @pacrob, @lla-dane  and @acul71 for their feedback and review. We plan to scale this module in dapps built using universal connectivity dapp. 

Reviewing it in detail. Looking forward to getting this merged soon.

**Comment by acul71** [comment]
@sumanjeet0012 
While reviewing this PR I had this type errors:
```python
(venv) luca@r17:~/PNL_Launchpad_Curriculum/Libp2p/py-libp2p$ make typecheck
pre-commit run mypy-local --all-files && pre-commit run pyrefly-local --all-files
run mypy with all dev dependencies present...............................Failed
- hook id: mypy-local
- exit code: 1

libp2p/discovery/rendezvous/pb/rendezvous_pb2.py:17: error: Call to untyped function "Default" in typed context  [no-untyped-call]
libp2p/discovery/rendezvous/messages.py:9: error: Module "libp2p.discovery.rendezvous.pb.rendezvous_pb2" has no attribute "Message"  [attr-defined]
libp2p/discovery/rendezvous/errors.py:5: error: Module "libp2p.discovery.rendezvous.pb.rendezvous_pb2" has no attribute "Message"  [attr-defined]
libp2p/discovery/rendezvous/service.py:26: error: Module "libp2p.discovery.rendezvous.pb.rendezvous_pb2" has no attribute "Message"  [attr-defined]
libp2p/discovery/rendezvous/client.py:33: error: Module "libp2p.discovery.rendezvous.pb.rendezvous_pb2" has no attribute "Message"  [attr-defined]
Found 5 errors in 5 files (checked 200 source files)

make: *** [Makefile:46: typecheck] Error 1

```
Fix here: https://github.com/sumanjeet0012/py-libp2p/pull/1

**Comment by sumanjeet0012** [comment]
@acul71 I have merged your PR. Could you please verify if everything is functioning as expected?

**Comment by acul71** [comment]
> @acul71 I have merged your PR. Could you please verify if everything is functioning as expected?

Hi @sumanjeet0012 
I had to updrade protobuf Python package from `4.25.8` → `6.32.1` to make it work
but in `pyproject.toml` is used 
```python
"protobuf>=4.25.0,<5.0.0",
```

Hi @pacrob can you help understand why this had happened ?
Is protobuf version needed to be upgraded ? ( remove constrain `<5.0.0`

**Problem:** After merging the PR, we encountered protobuf version compatibility issues causing import errors:

ImportError: cannot import name 'runtime_version' from 'google.protobuf'

**Root Cause:** Version mismatch between:
- **protoc compiler**: 32.0 (generates files expecting newer protobuf features)
- **protobuf Python package**: 4.25.8 (missing `runtime_version` module)

**Solution:** Upgraded protobuf Python package from `4.25.8` → `6.32.1`

**Results:**
- ✅ All type checking passes (mypy + pyrefly)
- ✅ All tests pass (765 passed, 3 skipped)
- ✅ Rendezvous module fully functional
- ✅ No import errors

**Note:** The `pyproject.toml` constraint `protobuf>=4.25.0,<5.0.0` should be updated to allow newer versions for better protoc compatibility.

Everything is now working as expected! 🎉

File: libp2p/discovery/rendezvous/client.py [hunk 1]
```diff
@@ -0,0 +1,365 @@
...
+
+
+class Registration:
+    """Represents a peer registration."""
+
+    def __init__(self, peer: PeerInfo, namespace: str, ttl: int):
+        self.peer = peer
+        self.namespace = namespace
+        self.ttl = ttl
+        self.expire_time = time.time() + ttl
```
Comment (pacrob) [inline libp2p/discovery/rendezvous/client.py]: This class doesn't appear to be used anywhere. What is it for?

File: libp2p/discovery/rendezvous/service.py [hunk 2]
```diff
@@ -0,0 +1,320 @@
...
+                    await stream.write(varint.encode(len(response_bytes)))
+                    await stream.write(response_bytes)
+
+        except Exception as e:
+            logger.error(f"Error handling stream from {peer_id}: {e}")
+        finally:
+            await stream.close()
+
+    def _handle_register(
+        self, peer_id: PeerID, register_msg: Message.Register
```
Comment (pacrob) [inline libp2p/discovery/rendezvous/service.py:139]: `peer_id` is not used in this function. Should it be? In `_handle_unregister`, you verify that `peer_id` and the peer id from the message are the same, should we do that here too?

File: libp2p/discovery/rendezvous/client.py (hunk 1 above)
Comment (sumanjeet0012) [reply libp2p/discovery/rendezvous/client.py]: yes it was not used anywhere and should be removed.

File: libp2p/discovery/rendezvous/service.py (hunk 2 above)
Comment (sumanjeet0012) [reply libp2p/discovery/rendezvous/service.py:139]: yes the validation should be there for registering a peer too.

**Comment by sumanjeet0012** [comment]
@seetadev A detailed discussion, along with a short demonstration video of Rendezvous Peer Discovery, is available here: [GitHub Discussion #955](https://github.com/libp2p/py-libp2p/discussions/955).

**Comment by seetadev** [comment]
@sumanjeet0012 : Thank you Sumanjeet. Appreciate your efforts. Reviewing the screencast and the discussion page too.

We will wait for feedback from @pacrob. Once the feedback points are marked resolved, we'll also do a final review together. Once I get a thumbs up from @pacrob, we will merge the PR. 

Will merge this before the upcoming release of py-libp2p. Looking forward to seeing all the peer discovery methods.

**Comment by sumanjeet0012** [comment]
@pacrob I have removed the class Registration and added the peer Id validation in _handle_register.
Now I am working on adding test cases for this PR.

File: libp2p/discovery/rendezvous/service.py (hunk 2 above)
Comment (pacrob) [reply libp2p/discovery/rendezvous/service.py:139]: looks good!

**Comment by sumanjeet0012** [comment]
@pacrob Ready for final review.

File: libp2p/discovery/rendezvous/service.py [hunk 3]
```diff
@@ -0,0 +1,332 @@
...
+        """Check if this registration has expired."""
+        return time.time() > self.expires_at
+
+    def to_protobuf_register(self) -> Message.Register:
+        """Convert to protobuf Register message."""
+        register = Message.Register()
+        register.ns = self.namespace
+        register.peer.id = self.peer_id.to_bytes()
+        register.peer.addrs.extend(self.addrs)
+        register.ttl = self.ttl
```
Comment (pacrob) [inline libp2p/discovery/rendezvous/service.py]: Non-blocking question: This will return the original ttl set, even if it's about to expire. Would it be helpful to peers if we proivded remaining ttl instead of the original value?

**Review by pacrob — APPROVED** [review]
Looks good! One question, but not blocking merge.

**Comment by seetadev** [comment]
@sumanjeet0012 : Thank you for your continued efforts on implementing Rendezvous module in py-libp2p. Appreciate it.

@pacrob : +1, thank you so much for your review and guidance. Appreciate it.

I spent sometime trying to understand where Rendezvous peer discovery module would be useful. Wish to recommend @sumanjeet0012 to share some test cases around it. We are very near to merging this PR. 

@sumanjeet0012 , @pacrob : Please visit https://github.com/libp2p/py-libp2p/discussions/965

File: libp2p/discovery/rendezvous/service.py (hunk 3 above)
Comment (sumanjeet0012) [reply libp2p/discovery/rendezvous/service.py]: yes, we should send the remaining TTL instead of initial TTL value.

**Comment by sumanjeet0012** [comment]
@pacrob I have changed the TTL calculation according to your suggestions. 
@seetadev The mentioned test cases are already added only scaling tests are not present. 

I don't know why kademlia test is failing in this PR.

**Comment by seetadev** [comment]
@sumanjeet0012 : Great to hear. Appreciate your efforts.

In reference to kad-dht test failure, it is not just your PR but a couple of others too. Documented it at https://github.com/libp2p/py-libp2p/discussions/949 . Wish if you could test locally and share review at https://github.com/libp2p/py-libp2p/pull/963. 

@yashksaini-coder is making good progress on the PR. Will ask him to add you as a collaborator.

**Comment by sumanjeet0012** [comment]
@seetadev Could you please confirm if there’s anything pending in this PR? If not, we can proceed with merging it.

**Comment by seetadev** [comment]
@sumanjeet0012 : Hi Sumanjeet. Did a final review. This PR is good to merge. Appreciate your great efforts.

Let us know try developing some examples using Rendezvous module in py-libp2p.
